language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

before_script:
  - cp .env.travis .env
  - composer self-update
  # Install dependencies
  - composer install --prefer-source --no-interaction --optimize-autoloader
  - mysql -e 'create database travis;'

script: vendor/bin/phpunit --coverage-clover storage/logs/clover.xml

after_success:
  - php vendor/bin/coveralls
