language: php

php:
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - nvm install node

before_script:
  # Init config
  - cp .env.travis .env
  # Create database
  - mysql -e 'create database travis;'
  # Install dependencies
  - composer self-update
  - composer install --prefer-source --no-interaction --optimize-autoloader
  - npm install
  - npm install gulp -g
  - bower install
  - gulp

script: vendor/bin/phpunit --coverage-clover storage/logs/clover.xml

after_success:
  - php vendor/bin/coveralls
